create table if not exists public.google_business_connections (
  id bigint generated by default as identity primary key,
  admin_user_id uuid not null references auth.users(id) on delete cascade unique,
  google_account_name text,
  google_location_name text,
  google_location_id text,
  google_location_title text,
  google_maps_url text,
  google_new_review_url text,
  vault_secret_id uuid,
  status text not null default 'connected' check (status in ('connected','needs_reauthorization','error')),
  connected_at timestamptz not null default now(),
  last_refreshed_at timestamptz,
  updated_at timestamptz not null default now()
);

alter table public.google_business_connections enable row level security;

create table if not exists public.google_business_reviews (
  id bigint generated by default as identity primary key,
  connection_id bigint not null references public.google_business_connections(id) on delete cascade,
  google_review_name text not null unique,
  reviewer_name text,
  reviewer_photo_url text,
  star_rating smallint not null check (star_rating between 1 and 5),
  comment text,
  create_time timestamptz,
  update_time timestamptz,
  google_reply text,
  google_reply_update_time timestamptz,
  published_on_website boolean not null default false,
  active boolean not null default true,
  sort_order integer not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.google_business_reviews enable row level security;

drop policy if exists google_business_reviews_public_read on public.google_business_reviews;
create policy google_business_reviews_public_read
  on public.google_business_reviews
  for select to anon, authenticated
  using (active = true and published_on_website = true);

drop policy if exists google_business_reviews_admin_all on public.google_business_reviews;
create policy google_business_reviews_admin_all
  on public.google_business_reviews
  for all to authenticated
  using (public.is_ivy_house_admin())
  with check (public.is_ivy_house_admin());

grant select on public.google_business_reviews to anon, authenticated;
grant insert, update, delete on public.google_business_reviews to authenticated;

create index if not exists google_business_reviews_connection_idx
  on public.google_business_reviews(connection_id, update_time desc);

create index if not exists google_business_reviews_public_idx
  on public.google_business_reviews(published_on_website, active, sort_order);

create or replace function public.set_google_business_refresh_token(p_admin_user_id uuid, p_refresh_token text)
returns uuid language plpgsql security definer set search_path = '' as $$
declare v_secret_id uuid; v_connection_id bigint;
begin
  if current_user not in ('service_role','postgres') then raise exception 'Not authorized'; end if;
  if p_refresh_token is null or length(trim(p_refresh_token)) = 0 then raise exception 'Refresh token is required'; end if;
  select c.id, c.vault_secret_id into v_connection_id, v_secret_id
    from public.google_business_connections c where c.admin_user_id = p_admin_user_id limit 1;
  if v_secret_id is null then
    v_secret_id := vault.create_secret(p_refresh_token,'ivy_house_google_reviews_' || p_admin_user_id::text,'Google Business Profile refresh token for Ivy House Reviews',null);
  else
    perform vault.update_secret(v_secret_id,p_refresh_token,null,null,null);
  end if;
  if v_connection_id is not null then
    update public.google_business_connections set vault_secret_id=v_secret_id,updated_at=now() where id=v_connection_id;
  end if;
  return v_secret_id;
end; $$;

revoke all on function public.set_google_business_refresh_token(uuid,text) from public, anon, authenticated;
grant execute on function public.set_google_business_refresh_token(uuid,text) to service_role;

create or replace function public.get_google_business_refresh_token(p_admin_user_id uuid)
returns text language plpgsql security definer set search_path = '' as $$
declare v_token text;
begin
  if current_user not in ('service_role','postgres') then raise exception 'Not authorized'; end if;
  select ds.decrypted_secret into v_token
    from public.google_business_connections c
    join vault.decrypted_secrets ds on ds.id=c.vault_secret_id
    where c.admin_user_id=p_admin_user_id limit 1;
  return v_token;
end; $$;

revoke all on function public.get_google_business_refresh_token(uuid) from public, anon, authenticated;
grant execute on function public.get_google_business_refresh_token(uuid) to service_role;

create or replace function public.update_google_business_connection(
  p_admin_user_id uuid,p_google_account_name text,p_google_location_name text,p_google_location_id text,
  p_google_location_title text,p_google_maps_url text,p_google_new_review_url text,p_status text default 'connected')
returns bigint language plpgsql security definer set search_path = '' as $$
declare v_id bigint;
begin
  if current_user not in ('service_role','postgres') then raise exception 'Not authorized'; end if;
  insert into public.google_business_connections(
    admin_user_id,google_account_name,google_location_name,google_location_id,google_location_title,
    google_maps_url,google_new_review_url,status,connected_at,updated_at)
  values(p_admin_user_id,p_google_account_name,p_google_location_name,p_google_location_id,p_google_location_title,
    p_google_maps_url,p_google_new_review_url,p_status,now(),now())
  on conflict(admin_user_id) do update set
    google_account_name=excluded.google_account_name,google_location_name=excluded.google_location_name,
    google_location_id=excluded.google_location_id,google_location_title=excluded.google_location_title,
    google_maps_url=excluded.google_maps_url,google_new_review_url=excluded.google_new_review_url,
    status=excluded.status,updated_at=now()
  returning id into v_id;
  return v_id;
end; $$;

revoke all on function public.update_google_business_connection(uuid,text,text,text,text,text,text,text) from public, anon, authenticated;
grant execute on function public.update_google_business_connection(uuid,text,text,text,text,text,text,text) to service_role;

create or replace function public.mark_google_business_refreshed(p_connection_id bigint,p_status text default 'connected')
returns void language plpgsql security definer set search_path = '' as $$
begin
  if current_user not in ('service_role','postgres') then raise exception 'Not authorized'; end if;
  update public.google_business_connections set status=p_status,
    last_refreshed_at=case when p_status='connected' then now() else last_refreshed_at end,
    updated_at=now() where id=p_connection_id;
end; $$;

revoke all on function public.mark_google_business_refreshed(bigint,text) from public, anon, authenticated;
grant execute on function public.mark_google_business_refreshed(bigint,text) to service_role;
